### ISSUE TITLE
parse_header Error trying to import adafruit_esp32spi.adafruit_esp32spi_wsgiserver

### ISSUE THREAD

**Issue by team3572** [adafruit/Adafruit_CircuitPython_ESP32SPI#109]
I'm new to the entire CircuitPython library.
Was following an online example to create a HTTP server and this line in the example is throwing an error...

`import adafruit_esp32spi.adafruit_esp32spi_wsgiserver as server`

Error is..
```
Traceback (most recent call last):
  File "code.py", line 1, in <module>
  File "adafruit_esp32spi/adafruit_esp32spi_wsgiserver.py", line 34, in <module>
ImportError: cannot import name parse_headers
```
I do have the adafruit_requests library installed.

But maybe I have something incorrect in my installation.
I do have other things working using CircuitPython so in general I am running code fine.

**Comment by tannewt** [comment]
Oops! I think I broke this. `parse_headers` is not actually part of the requests API. We'll need to pull the implementation into this library. The code is here: https://github.com/adafruit/Adafruit_CircuitPython_Requests/blob/master/adafruit_requests.py#L268

Do you want to try that? You can get guidance on [our Discord](https://adafru.it/discord)

**Comment by Anton-2** [comment]
Fixed in #115 . With this PR I was able to make a WSGI app on a MatrixPortal allowing uploading of pictures...

**Comment by tekktrik** [comment]
Looking through old issues, it looks like this may be fixed?

**Comment by anecdata** [comment]
Closing. The ESP32SPI WSGI server was deprecated in #167 and #181, in favor of https://github.com/adafruit/Adafruit_CircuitPython_HTTPServer
