### ISSUE TITLE
TypeError when calling ESPSPI_WiFiManager.signal_strength

### ISSUE THREAD

**Issue by mikejc58** [adafruit/Adafruit_CircuitPython_ESP32SPI#110]
In adafruit_esp32spi_wifimanager.py, ESPSPI_WiFiManager.signal_strength() accesses self.esp.rssi as a function, but it is a property.

`return self.esp.rssi()`  should be `return self.esp.rssi`

**Comment by siddacious** [comment]
Fixed via #111
