### ISSUE TITLE
Typo in "wifitest" page hosted on the Adafruit website

### ISSUE THREAD

**Issue by nothans** [adafruit/Adafruit_CircuitPython_ESP32SPI#119]
I found a small typo on the "wifitest" page hosted at the Adafruit website: http://wifitest.adafruit.com/testwifi/index.html

Returns: This is a test of Adafruit WiFi! If you can read this, its working :)

*its* should *it is* - I understand why you might not want to use the apostrophe.

**Comment by ladyada** [comment]
yes - i personally dislike apostrophes :)
