### ISSUE TITLE
Documentation on status LED?

### ISSUE THREAD

**Issue by ajs256** [adafruit/Adafruit_CircuitPython_ESP32SPI#120]
I can't seem to find documentation on how this library controls the NeoPixel on my MatrixPortal. Could someone please point me to where I could find that?

**Comment by jerryneedell** [comment]
This is probably not what you were asking for but hopefully it will help.
It is used by the Wifi manager  https://learn.adafruit.com/adafruit-pyportal/internet-connect#wifi-manager-3034791-36 , but you are correct, the actual usage is not documented. The simplest thing now would be to look at the code for places where the pixel_status is set -- for example 
https://github.com/adafruit/Adafruit_CircuitPython_ESP32SPI/blob/master/adafruit_esp32spi/adafruit_esp32spi_wifimanager.py#L139
and
https://github.com/adafruit/Adafruit_CircuitPython_ESP32SPI/blob/master/adafruit_esp32spi/adafruit_esp32spi_wifimanager.py#L142

show it being set red  (100,0,0) before then green(0,100,0) after "connecting".

**Comment by FoamyGuy** [comment]
closed by #148
