### ISSUE TITLE
Feather M4 Express not connecting with Air Lift ESP32 Coprocessor after update to NINA_W102-1.7.4

### ISSUE THREAD

**Issue by LAWBear** [adafruit/Adafruit_CircuitPython_ESP32SPI#144]
Purchased Feather M4 Express to allow use of Air Lift ESP32 Coprocessor breakout board via SPI. 
Previous test with original Air Lift firmware using Feather M0 Adalogger were successful using WIFINA examples.  

Following detailed instructions, I updated firmware on Air Lift using SerialPassThru on new Feather M4 Express, and reflashed Air Lift with NINAW102-1.7.4 as clear instructions provided:
![Capture](https://user-images.githubusercontent.com/65572901/143299514-76f9358e-8c1b-485e-9c1c-0c15aa19e0c8.JPG)
The above output assumed success of the update as instructed, however EXTENSIVE testing of various CircuitPython examples from Python 7 bundles all fail with similar errors (timed out waiting for SPI char) as follows:
ESP32 SPI webclient test
Traceback (most recent call last):
  File "code.py", line 50, in <module>
  File "/lib/adafruit_esp32spi/adafruit_esp32spi.py", line 335, in status
  File "/lib/adafruit_esp32spi/adafruit_esp32spi.py", line 325, in _send_command_get_response
  File "/lib/adafruit_esp32spi/adafruit_esp32spi.py", line 292, in _wait_response_cmd
  File "/lib/adafruit_esp32spi/adafruit_esp32spi.py", line 271, in _wait_spi_char
RuntimeError: Timed out waiting for SPI char

I am desperate for a kind wizard to advise my errors and lead to my hope of implementing the BLE capabilities of the Feather M4 Express with Air Lift ESP32 Coprocessor breakout board.

**Comment by anecdata** [comment]
Should work, I have an identical configuration, but I think this is more of a support issue. Can you post about it on the Adafruit Discord #help-with-CircuitPython, (or if not that then in the Adafruit support forums)?

**Comment by JayToltTech** [comment]
@LAWBear I have an identical configuration and I had your problem *until* I flashed to W102-1.7.4 which fixed the problem.

My suspicion would be that your flash didn't work as expected.  I had to flash a few times to get it right, though I don't think I saw a 'false positive' where it said it flashed but didn't like seems to be in your case.

**Comment by anecdata** [comment]
And just to be squeaky-clean about it, you can use the `erase_flash` option before the flashing step.

**Comment by LAWBear** [comment]
Many thanks to the wizards, I will implement all checks and suggestions soonest.

**Comment by dhalbert** [comment]
Closing as possibly resolved, please reopen if not.
