### ISSUE TITLE
Expose RSSI in WifiManager for the established connection

### ISSUE THREAD

**Issue by siddacious** [adafruit/Adafruit_CircuitPython_ESP32SPI#15]
It would be great to be able to do something like `wifi.rssi` or more descriptively `wifi.signal_strength` so that one could periodically log/display the signal strength.

**Comment by brentru** [comment]
Great idea - you could expose this method: https://github.com/adafruit/Adafruit_CircuitPython_ESP32SPI/blob/master/adafruit_esp32spi/adafruit_esp32spi.py#L386

**Comment by makermelissa** [comment]
That should be easy enough to do.

**Comment by makermelissa** [comment]
Fixed #15 via #16 and #18.
