### ISSUE TITLE
adafruit_esp32 TimeoutError

### ISSUE THREAD

**Issue by gadjodilo83** [adafruit/Adafruit_CircuitPython_ESP32SPI#176]
**CircuitPython version**
Adafruit CircuitPython 8.0.0-beta.6 on 2022-12-21; Adafruit Matrix Portal M4 with samd51j19
Board ID:matrixportal_m4

**Code/REPL**
Datei "code.py", Line 118, in <module>
  Datei "adafruit_portalbase/__init__.py", Zeile 488, in get_local_time
  Datei "adafruit_portalbase/network.py", Zeile 240, in get_local_time
  Datei "adafruit_portalbase/network.py", Zeile 209, in get_strftime
  Datei "adafruit_requests.py", Zeile 820, in get
  Datei "adafruit_requests.py", Zeile 676, in request
  Datei "adafruit_esp32spi/adafruit_esp32spi_socket.py", Zeile 138, in recv
  Datei "adafruit_esp32spi/adafruit_esp32spi_socket.py", Zeile 210, in available
  Datei "adafruit_esp32spi/adafruit_esp32spi.py", Zeile 776, in socket_available
  Datei "adafruit_esp32spi/adafruit_esp32spi.py", Zeile 332, in _send_command_get_response
  Datei "adafruit_esp32spi/adafruit_esp32spi.py", Zeile 299, in _wait_response_cmd
  Datei "adafruit_esp32spi/adafruit_esp32spi.py", Zeile 278, in _wait_spi_char
TimeoutError: Timed out waiting for SPI char
]0;🐍278@adafruit_esp32spi/adafruit_esp32 TimeoutError | 8.0.0-beta.6\

Line 118 is: **matrixportal.get_local_time()**

I've had this problem for a year now. Up to now no update could help and fix the problem.
Can anyone help me to solve this problem without microcontroller reset?

Thanks
Marc

**Comment by makermelissa** [comment]
The error is happening in the Adafruit_CircuitPython_ESP32SPI library, so I transferred it. However it looks like somebody else opened an issue with the same error in #170.
