### ISSUE TITLE
building NINA firmware -- version still 1.2.1

### ISSUE THREAD

**Issue by jerryneedell** [adafruit/Adafruit_CircuitPython_ESP32SPI#19]
When I try to build my own copy of the NINA_W102 firmware --  It compiles fine with the latest version of the esp-idf  but I found that the  Firmware Version is still set to 1.2.1  in the adafruit/nina-fw repo https://github.com/adafruit/nina-fw/blob/master/main/CommandHandler.cpp#L28   Is this repo up to date?  How did you get version 1.2.2 in the posted NINA_W102_17_FEB_2018.bin?   My build seems to work but it reports version 1.2.1.

**Comment by ladyada** [comment]
i think i hand changed it later

**Comment by ladyada** [comment]
please try it out and if it works, you can submit a PR there!

**Comment by jerryneedell** [comment]
ok -- will do

**Comment by jerryneedell** [comment]
PR submitted
