### ISSUE TITLE
No context manager for socket

### ISSUE THREAD

**Issue by anecdata** [adafruit/Adafruit_CircuitPython_ESP32SPI#195]
Lack of `with` context manager makes it harder to write code / use libraries, compatible across radios (sources of sockets; e.g., native wifi, WIZnet, ESP32SPI).

Example:
https://github.com/adafruit/Adafruit_CircuitPython_NTP/pull/31
```
Traceback (most recent call last):
  File "<stdin>", line 38, in <module>
  File "adafruit_ntp.py", line 77, in datetime
AttributeError: 'socket' object has no attribute '__exit__'
```

**Comment by dhalbert** [comment]
If you feel so inclined, a PR would be welcome.
