### ISSUE TITLE
HTTP Server example is empty and this library is not compatible with Adafruit_CircuitPython_HTTPServer

### ISSUE THREAD

**Issue by tedivm** [adafruit/Adafruit_CircuitPython_ESP32SPI#211]
I'm trying to launch a web server on a board with an esp coprocessors for wifi. Unfortunately the Adafruit_CircuitPython_HTTPServer library does not appear to work with the existing socket implimentation that exists with this library, and the alternative example [is just an empty file](https://github.com/adafruit/Adafruit_CircuitPython_ESP32SPI/tree/main/examples/server).

**Comment by dhalbert** [comment]
See https://github.com/adafruit/Adafruit_CircuitPython_WSGI, which does have ESP32SPI examples.

**Comment by tedivm** [comment]
Thank you so much!
