### ISSUE TITLE
change local time example to use adafruit.io 

### ISSUE THREAD

**Issue by jerryneedell** [adafruit/Adafruit_CircuitPython_ESP32SPI#26]
Should the esp32spi_localtime.py example be updated to use adafruit.io instead of worldtimeapi as was done for PyPortal?
Would it be good to show how to use both? Two examples or use comment blocks to allow either?

Or just close this if you want to leave it as is?

**Comment by ladyada** [comment]
i think...this is ok to keep as is because its a good basic json demo - pyportal its hidden :)
