### ISSUE TITLE
It took a long time to connect to WiFi.

### ISSUE THREAD

**Issue by xelll** [adafruit/Adafruit_CircuitPython_ESP32SPI#31]
i use raspberry pi zero with esp-wroom-32, it took too long to connect ap. about 30 sec
   https://github.com/adafruit/Adafruit_CircuitPython_ESP32SPI/blob/c2e0fd2b094d187f4aa52f7180c7a11b652250fc/adafruit_esp32spi/adafruit_esp32spi.py#L418-L441

**Comment by ladyada** [comment]
im surprised it worked at all, it's meant for small microcontrollers, but i dont see why it wouldn't work

**Comment by xelll** [comment]
ok， but my problem is esp32 connect to ap took too long time

**Comment by ladyada** [comment]
there's not much we can do about it I think, it takes as long as ESP32 takes - you should use a USB WiFi adapter for Linux wifi usage :)
