### ISSUE TITLE
some bug in https://github.com/adafruit/nina-fw/

### ISSUE THREAD

**Issue by xelll** [adafruit/Adafruit_CircuitPython_ESP32SPI#32]
https://github.com/adafruit/nina-fw/blob/35966a57f91f2de73d3f935f45a6e3d08e8b5d51/main/CommandHandler.cpp#L1093

this delay should be more big, otherwise will occur memory leak.

**Comment by ladyada** [comment]
@xelll thanks - what values did you try?

**Comment by xelll** [comment]
> @xelll thanks - what values did you try?

100...
