### ISSUE TITLE
Companion firmware binaries

### ISSUE THREAD

**Issue by rdagger** [adafruit/Adafruit_CircuitPython_ESP32SPI#35]
Are there pre-built binaries for the companion firmware?

**Comment by docmollo** [comment]
The official firmware is available from the Learn guide (https://learn.adafruit.com/adding-a-wifi-co-processor-to-circuitpython-esp8266-esp32/firmware-files#esp32-only-spi-firmware-3-8). If you're looking for a pre-compiled binary with WPA2 Enterprise support, that hasn't been released yet, as the support just got merged.

**Comment by ladyada** [comment]
@doc dya wanna attach a file here and then i can put it in the learn guide

**Comment by docmollo** [comment]
Sure! Here ya go.

[NINA_W102-1.3.0.zip](https://github.com/adafruit/Adafruit_CircuitPython_ESP32SPI/files/3051756/NINA_W102-1.3.0.zip)

**Comment by ladyada** [comment]
@rdagger please try it!

**Comment by rdagger** [comment]
@ladyada Thanks, it works great!

**Comment by docmollo** [comment]
Thanks @rdagger! You might be the first person to try out the new code...certainly the first to try out my binary firmware file. Glad to hear it all works for you! :blush:

**Comment by ladyada** [comment]
https://learn.adafruit.com/adding-a-wifi-co-processor-to-circuitpython-esp8266-esp32/firmware-files
