### ISSUE TITLE
Expose additional NINA FW SPI command handlers (AKA Release the Kraken)

### ISSUE THREAD

**Issue by anecdata** [adafruit/Adafruit_CircuitPython_ESP32SPI#36]
The ESP32 module used as an ESP32SPI co-processor is a bit of monolith. It does its job silently, in the dark, with no external user controls or indicators. But there is untapped power even as a co-processor.

This issue is an enhancement request to expose additional command handlers from CommandHandler.cpp from the adafruit/nina-fw, especially setPinMode, setDigitalWrite, and setAnalogWrite.

There are also other potentially interesting command handlers, but I'm not sure which are fully implemented even in the C code; I don't seem to get much meaningful returned from getTime or getTemperature for example (I could easily be doing something wrong).

In Arduino, the Airlift breakout can control its on-board red, green, and blue LEDs via the adafruit/WiFiNINA library. But for CircuitPython on a separate M4 processor, the ESP32SPI library would need to expose additional command handlers to be able to control the GPIO pins.

Potentially, _many_ ESP32 co-processor pins could be made available to CircuitPython, depending on form factor:

• ESP 32 Airlift breakout GPIO/A pins: 
**25**[Green LED], **26**[Red LED], **27**[Blue LED]

• ESP32 Huzzah32 breakout GPIO/A pins: 
15,2,0,4,16,17,5,18,19,21,22,23,13,12,14,**27**,**26**,**25**,33,32,35,34,39,36

• ESP32 Huzzah32 Feather GPIO/A pins: 
A0/**26**,A1/**25**,A2/34,A3/39,A4/36,A5/4,21,13[LED],12[PULLDOWN],**27**,33,15,32,14

• ESP32 Airlift Feather GPIO/A pins (speculation based on #LEEK): 
A0/**26**, A1/**25**, A2/34, A3/39

[ P.S. I spent several hours trying to do this myself, but between the python code, SPI protocol, and layers of C code, it's beyond my current level. I'll keep digging though. I'm sure someone more skilled in the arts would look at it and say "oh, of course you'd just..." ;-) ]

**Comment by cpforbes** [comment]
I just submitted PR #38 that exposes the low level GPIO commands already in the nina-fw. Nothing specific to a particular ESP32 board.

**Comment by ladyada** [comment]
nice!
anyone wanna test it out? @brentru should be able to twiddle the RGB LEDs on the AirLift breakout

**Comment by brentru** [comment]
Yup, I’ll test and review tomorrow.

**Comment by anecdata** [comment]
Airlift Breakout RGB LEDs are on! <img width="802" alt="RGB" src="https://user-images.githubusercontent.com/16617689/56550893-79639500-654c-11e9-947d-26f0f0fcc9f8.png">

**Comment by ladyada** [comment]
:D

**Comment by anecdata** [comment]
Pin #13 RED LED on Feather ESP32 is on! 
<img width="997" alt="13" src="https://user-images.githubusercontent.com/16617689/56551281-8a60d600-654d-11e9-90c5-d9153caccd49.png">

**Comment by brentru** [comment]
Merged into master and released!
