### ISSUE TITLE
PyPortal pynt WiFi not working

### ISSUE THREAD

**Issue by evanthomas** [adafruit/Adafruit_CircuitPython_ESP32SPI#86]
I just received 2 pyportals, a normal and a pynt. The normal works fine but the pynt cannot connect to my home AP. I have tried CP versions 4.0.0-beta5, 4.1.2 and 5.0.0-beta4. 

The home AP gives the message 'No such ssid'. It has spaces in the name, no idea if that is relevant.

I am able to intermittently connect to my iphone (no spaces in the SSID) but it usually fails with 'Failed to connect to ssid'. Even when it does connect, I not able retrieve data over WiFi.

**Comment by ladyada** [comment]
hi please post in the forum - this is not where we are able to answer tech support :)
